### ISSUE TITLE
Fails to build with curl 7.62.0

### ISSUE THREAD

**Issue by mones** [dinhviethoa/libetpan#313]
Hi Hoa,

It has been reported that libetpan 1.9.1 fails to build with new curl 7.62.0 with the following error:

> newsfeed.c: In function 'curl_error_convert':
> newsfeed.c:538:3: error: duplicate case value
>    case CURLE_SSL_CACERT:
>    ^~~~
> newsfeed.c:533:3: note: previously used here
>    case CURLE_SSL_PEER_CERTIFICATE:
>    ^~~~
> make[9]: *** [Makefile:579: newsfeed.lo] Error 1

At first sight looks like an easy fix, but there's more info which could be relevant on the original bug report: https://bugs.debian.org/913383

Thanks in advance!

**Comment by mones** [comment]
Hi there Hoa! Any chance of getting an official patch for this?

**Comment by mones** [comment]
Uh, sorry! Didn't noticed it was already fixed ;-)

Many thanks!
